refactor: migrate to TypeScript
JoshuaKGoldberg/package.json-validator pull request #110
Opened 2024-12-30 17:16 UTC by michaelfaith

## PR Checklist

- [x] Addresses an existing open issue: fixes #91 
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/package-json-validator/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/package-json-validator/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

This change migrates the project to TypeScript.  Beyond providing types now, as well as an ESM option, the aim was to not change the API in a breaking way.

In doing this migration, I actually found at least one bug (TypeScript doing its job!).  In `validate`, `getSpecMap` was called, and immediately after there was an if condition to check if the result that came back was `false`, which would indicate the requested spec name was bad.  However the if condition checked if `specName` was false, rather than the result of the `getSpecMap` function.  That would have allowed people to pass in nonsense specNames and throwing an error later when attempting to access `map`.  I've fixed that here.

I did put a TODO in though to consider deprecating the one named PJV export, in favor of directly exporting the functions and constants.  This would make the API more tree-shakable and (in my opinion) more straightforward.  But that should be a separate change, if implemented.

The other quality of life stuff I adjusted:
- Added TsDoc in more places
- Changed concatted strings to template strings

Note: The GH diff is awful on this.  VS Code's diff was much better.  It also seemed to lose track of the `git mv` (even though it got it right in the individual commits)

![image](https://github.com/user-attachments/assets/24b6a4b3-ff6d-442a-bd3c-518755c82b19)

2025-01-03 21:19 UTC, JoshuaKGoldberg requested changes
What a great start, thank you for taking this on! ❤️ 

Left some comments here and there - I think the biggest change request from me is fixing linting to handle the new TypeScript syntax.

2025-01-03 21:19 UTC, JoshuaKGoldberg commented on tsconfig.json
> +		"outDir": "dist",
Since `noEmit` is enabled, this isn't necessary:

```suggestion
```

2025-01-03 21:19 UTC, JoshuaKGoldberg commented on tsup.config.ts
> +	outDir: "dist",
Both `dist` and `lib` are totally reasonable outputs, but since https://github.com/JoshuaKGoldberg/create-typescript-app uses `lib`, let's use that here:

```suggestion
	outDir: "lib",
```

I'm soon going to automate keeping all my packages up-to-date with CTA and having discrepancies like this will make that more complicated.

2025-01-03 21:19 UTC, JoshuaKGoldberg commented on src/PJV.test.ts
> +	const out: Record<string, any> = {
[Style] This should be linted to:

```suggestion
	extra: Record<string, unknown> = {},
): Record<string, unknown> => {
	const out: Record<string, unknown> = {
```

2025-01-03 21:19 UTC, JoshuaKGoldberg commented on src/PJV.ts
> +	value: any[] | boolean | string | object,
```suggestion
	value: unknown[] | boolean | string | object,
```

2025-01-03 21:19 UTC, JoshuaKGoldberg commented on src/PJV.types.ts
> +	validate?: (...args: any[]) => string[];
[Non-Actionable] It would be nice to use something more safe like `unknown[]` or `never[]` here... but I tried that out locally and it's a lot of work. I got through changing this to `type BaseFieldSpec<Args extends never[]>` and lost interest. So I think that's fine as a separate not-urgent-at-all issue.

2025-01-03 21:19 UTC, JoshuaKGoldberg commented on src/PJV.types.ts
[Question] I've more often seen types files like this be named `types.ts`. Any reason not to use that shorter name here?

2025-01-03 21:19 UTC, JoshuaKGoldberg commented on src/index.ts
> +export { PJV } from "./PJV";
I think types like `SpecName` will be useful for folks:

```suggestion
export { PJV } from "./PJV";
export type { SpecName, SpecType } from "./PJV.types"; 
```

_(or `from "./types"` per the comment in that file)_

2025-01-03 21:19 UTC, JoshuaKGoldberg commented on src/PJV.ts
> + */
I don't think this comment is particularly helpful anymore 😄 

```suggestion
```

2025-01-03 21:19 UTC, JoshuaKGoldberg commented on package.json
> +		"typescript": "^5.7.2",
I can't comment in `eslint.config.js`, but a good chunk of core ESLint rules are broken and/or redundant with TypeScript. This'll also need to add typescript-eslint there:

```suggestion
		"typescript": "^5.7.2",
		"typescript-eslint": "^8.19.0",
```

2025-01-03 21:19 UTC, JoshuaKGoldberg commented on src/PJV.ts
> +// exporting the functions and constants?
> I did put a TODO in though to consider deprecating the one named PJV export, in favor of directly exporting the functions and constants. This would make the API more tree-shakable and (in my opinion) more straightforward. But that should be a separate change, if implemented.

Agreed, I think that'd be a good followup.

2025-01-03 21:50 UTC, michaelfaith commented on src/PJV.types.ts
This just comes from working on large monorepo codebases.  If you have several `types.ts` files across a codebase, it really hurts findability.  So my convention has always been to prefix it with the name of the the thing it's related to.  (e.g. A React Component or whatever the main thing the types relate to is).  This is a very single-purposed repo, so totally cool with just changing it to `types.ts` if you prefer.

2025-01-03 21:51 UTC, michaelfaith commented
Thanks for the thorough review.  I'll work on addressing those.

2025-01-03 21:52 UTC, michaelfaith commented on package.json
> +		"typescript": "^5.7.2",
Do you have a preference with TS-ESLint config(s) I use?

2025-01-05 20:13 UTC, michaelfaith commented on src/PJV.types.ts
> +	validate?: (...args: any[]) => string[];
For now, I've updated it to `validate?: (name: string, obj: any) => string[];` which limits the `any` to just the one param.  We can work on improving that as a follow-up

2025-01-05 20:44 UTC, michaelfaith commented on src/PJV.ts
> +// exporting the functions and constants?
Opened https://github.com/JoshuaKGoldberg/package-json-validator/issues/124 to track

2025-01-11 20:30 UTC, michaelfaith commented
@JoshuaKGoldberg curious if you have any additional feedback on this change?

2025-01-13 02:01 UTC, JoshuaKGoldberg commented
Hey sorry got swamped the last few weeks - did not mean to leave this hanging. Checking now!

2025-01-13 02:01 UTC, JoshuaKGoldberg commented on src/PJV.types.ts
> +	validate?: (...args: any[]) => string[];
Nice spot, I hadn't noticed that was doable. 🚀

2025-01-13 02:05 UTC, JoshuaKGoldberg commented
Btw, just as a precaution, I renamed this to `feat:`. It does change the internal structure a bit.

2025-01-13 02:17 UTC, JoshuaKGoldberg requested changes
Cool, progress! I think the `.ts` changes all look great. 🚀 

Left some comments around the tooling around them. Looking forward to this!

2025-01-13 02:17 UTC, JoshuaKGoldberg commented on eslint.config.js
> +const tsESLint = require("typescript-eslint");
[Style] From https://typescript-eslint.io/getting-started, we generally call it this:

```suggestion
const tseslint = require("typescript-eslint");
```

2025-01-13 02:17 UTC, JoshuaKGoldberg commented on eslint.config.js
> +			"n/hashbang": "off",
Heh, this is why I normally still include a `bin/*` file that imports a `lib/*` file: https://github.com/JoshuaKGoldberg/prune-github-notifications/blob/247c5cc477b063d6772823ff6f37c2207b1095c7/bin/index.js

I personally prefer having a small `bin` file the way that repo does. But I don't feel strongly. I suppose either we have a more complicated ESLint config or an extra folder + file. If you strongly prefer the current approach, I don't mind. 🙂

2025-01-13 02:17 UTC, JoshuaKGoldberg commented on eslint.config.js
> +]);
```suggestion
);
```

2025-01-13 02:17 UTC, JoshuaKGoldberg commented on eslint.config.js
> +module.exports = tsESLint.config([
[Style] `tseslint.config` flattens arrays for us ✨ 

```suggestion
module.exports = tsESLint.config(
```

2025-01-13 02:17 UTC, JoshuaKGoldberg commented on eslint.config.js
> +	{
[Style] Could you please merge this object with the other `rules`? I.e.:

```ts
	eslint.configs.recommended,
	n.configs["flat/recommended"],
	tsESLint.configs.recommended,
	{
		linterOptions: {
			reportUnusedDisableDirectives: "error",
		},
		rules: {
			"no-undef": "off",
			"no-useless-escape": "off",
			// TS handles this for us
			"n/no-missing-import": "off",
		},
	},
```

I've triaged enough user pain over complicated ESLint configs to have a drive to simplify them as much as possible, whenever possible. 😂

2025-01-13 02:17 UTC, JoshuaKGoldberg commented on .github/workflows/build.yml
> +      - run: node ./lib/index.js
[Tooling] How about running the bin on itself as a form of checking that?

```suggestion
      - run: node ./lib/bin/pjv.mjs
```

2025-01-13 02:17 UTC, JoshuaKGoldberg commented on package.json
> +		"type-check": "tsc --noEmit"
Since this is already set in `tsconfig.json`:

```suggestion
		"type-check": "tsc"
```

2025-01-13 02:17 UTC, JoshuaKGoldberg commented on src/bin/pjv.ts
[Bug?] I tried running this locally:

```shell
gh pr checkout 110
pnpm i
pnpm build
node ./lib/bin/pjv.mjs
```

...and got:

```plaintext
$ node ./lib/bin/pjv.mjs
node:internal/modules/esm/resolve:260
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/josh/repos/package-json-validator/lib/PJV' imported from /Users/josh/repos/package-json-validator/lib/bin/pjv.mjs
    at finalizeResolution (node:internal/modules/esm/resolve:260:11)
    at moduleResolve (node:internal/modules/esm/resolve:921:10)
    at defaultResolve (node:internal/modules/esm/resolve:1132:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:557:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:526:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:249:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:126:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/josh/repos/package-json-validator/lib/PJV'
}

Node.js v22.4.1
```

This also happens with `npx .`:

```plaintext
 $ npx .
node:internal/modules/esm/resolve:260
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/josh/repos/package-json-validator/lib/PJV' imported from /Users/josh/repos/package-json-validator/lib/bin/pjv.mjs
    at finalizeResolution (node:internal/modules/esm/resolve:260:11)
    at moduleResolve (node:internal/modules/esm/resolve:921:10)
    at defaultResolve (node:internal/modules/esm/resolve:1132:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:557:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:526:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:249:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:126:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/josh/repos/package-json-validator/lib/PJV'
}

Node.js v22.4.1
```

Bug? Or am I holding it wrong?

2025-01-13 19:03 UTC, michaelfaith commented on eslint.config.js
> +			"n/hashbang": "off",
One of the downsides to that pattern, and why I don't generally go with it, is that the bin/*.js file is importing from a file that will only exist after build, which impacts our ability to do some amount of static analysis on it.

2025-01-13 19:29 UTC, michaelfaith commented on eslint.config.js
> +const tsESLint = require("typescript-eslint");
Updated

2025-01-13 19:29 UTC, michaelfaith commented on eslint.config.js
> +module.exports = tsESLint.config([
updated

2025-01-13 19:30 UTC, michaelfaith commented on eslint.config.js
> +	{
Fair enough.  I organized it so that the config turning off the rules was directly after the config that enabled it, but that may not be as obvious and may not even be useful, since rules names have plugin prefixes.

2025-01-13 19:30 UTC, michaelfaith commented on .github/workflows/build.yml
> +      - run: node ./lib/index.js
Updated

2025-01-13 19:32 UTC, michaelfaith commented on src/bin/pjv.ts
Updated.  the imports didn't have explicit extensions.  I fixed that.  The one downside to having that be explicit without extension rewrite, is that the `mjs` files will be importing from the `js` files.  Ideally, tsup would rewrite those for us, so that the relative import extension matches the module type, but it doesn't currently support that. This works now, but something to possibly iterate on in the future.

Opened this for tracking on the tsup side: https://github.com/egoist/tsup/issues/1271

2025-01-15 12:26 UTC, JoshuaKGoldberg commented on package.json
> +		"typescript": "^5.7.2",
`recommended` works for now. Eventually I'll (semi-automatically) migrate this to my template that applies `strictTypeChecked` and `stylisticTypeChecked`. 👍

2025-01-15 12:29 UTC, JoshuaKGoldberg commented on eslint.config.js
> +			"n/hashbang": "off",
👍 no complaint from me for now. Thanks!

2025-01-15 12:29 UTC, JoshuaKGoldberg approved these changes
🔥🔥🔥

This is lovely, thanks a million for putting so much work into this! I'll do a few small personal-nitpick-subjective-opinion touchups and make a release.

2025-01-15 12:29 UTC, JoshuaKGoldberg commented on eslint.config.js
> +	// Global ignores
Nit: no need, these are implied 🙂 

```suggestion
```

2025-01-15 12:30 UTC, JoshuaKGoldberg commented on src/bin/pjv.ts
Yeah TSup has been kind of falling out of latest-and-shiniest status for me for a bit ☹️. Pity.

2025-01-15 12:49 UTC, merged