feat: migrate to yargs
JoshuaKGoldberg/package.json-validator pull request #94
Opened 2024-09-12 19:43 UTC by de-don

closes #86

2024-09-12 19:47 UTC, de-don commented
@JoshuaKGoldberg looks like CI is not configured properly :(

2024-10-10 21:48 UTC, Cellule commented
@JoshuaKGoldberg Any chance we can get this merged in?

2024-10-10 21:50 UTC, Cellule commented
> @JoshuaKGoldberg looks like CI is not configured properly :(

Because the pipeline are defined in https://github.com/JoshuaKGoldberg/package.json-validator/pull/89
Normally you shouldn't put a pipeline required in the settings until it has been merged in

2024-10-10 22:16 UTC, JoshuaKGoldberg commented
Ha, yeah, I'd run [`create-typescript-app`](http://github.com/JoshuaKGoldberg/create-typescript-app) and meant to merge, then got pulled away for other things. I should be able to get to #89 and this Soon™️. Sorry for the delay!

2024-10-15 19:48 UTC, JoshuaKGoldberg requested changes
Sorry again for the wait here. I don't think it's working? Am I missing something?

2024-10-15 19:48 UTC, JoshuaKGoldberg commented on bin/pjv
> +	.parse();
🤔 Am I doing something wrong? When I put in a `console.log({ options })` here, `recommendations` and `warnings` aren't detected:

```plaintext
joshgoldberg ~/repos/package.json-validator $ node bin/pjv -r -w   
{
  options: {
    _: [],
    r: false,
    recommendations: false,
    w: false,
    warnings: false,
    filename: 'package.json',
    f: 'package.json',
    spec: 'npm',
    s: 'npm',
    quiet: false,
    q: false,
    '$0': 'bin/pjv'
  }
}
{ valid: true }
joshgoldberg ~/repos/package.json-validator $ node bin/pjv --recommendations --warnings
{
  options: {
    _: [],
    recommendations: false,
    r: false,
    warnings: false,
    w: false,
    filename: 'package.json',
    f: 'package.json',
    spec: 'npm',
    s: 'npm',
    quiet: false,
    q: false,
    '$0': 'bin/pjv'
  }
}
```

They are on `main`.

2024-10-16 14:56 UTC, de-don commented
@JoshuaKGoldberg sorry, I forgot to mark these options as boolean. Should be fixed

2024-10-17 21:42 UTC, JoshuaKGoldberg approved these changes
💯 this is lovely, thanks @de-don!

2024-10-17 21:42 UTC, merged

2024-10-17 21:43 UTC, JoshuaKGoldberg commented
@all-contributors please add @de-don for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

2024-10-17 22:22 UTC, Cellule commented
Awesome thanks!
I opened a PR to update to 0.7.0 in https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/pull/569